FROM httpd:2.4
VOLUME /mydata
COPY check.py .
RUN touch mylastfile.html
RUN touch mydata/log.html
RUN apt-get update -y
RUN apt install cron -y && apt install python3 -y
RUN service cron start
COPY activatepy.sh . 
